In [13]:
import numpy as np

In [14]:
X = np.random.random((5,5))
X

array([[0.72145439, 0.10128368, 0.17771835, 0.43791404, 0.25549533],
       [0.5965117 , 0.49385104, 0.93303204, 0.18387156, 0.56162949],
       [0.35627427, 0.20324525, 0.75932104, 0.5465047 , 0.97133986],
       [0.07184414, 0.11502447, 0.59969255, 0.66423107, 0.14246451],
       [0.80826518, 0.77269465, 0.65875663, 0.15304629, 0.96770361]])

In [15]:
M = X.mean()
M

np.float64(0.49012679386126945)

In [16]:
STD= X.std()
STD

np.float64(0.29010076584291083)

In [17]:
Z = (X-M)/STD
Z

array([[ 0.79740429, -1.34037258, -1.07689631, -0.17998144, -0.808793  ],
       [ 0.36671709,  0.01283777,  1.52672899, -1.05568571,  0.24647537],
       [-0.4614001 , -0.98890309,  0.92793361,  0.19433903,  1.65877904],
       [-1.44185297, -1.29300702,  0.37768172,  0.60015104, -1.19841905],
       [ 1.09664788,  0.97403348,  0.5812802 , -1.16194281,  1.64624458]])

In [18]:
np.save("X_normalized.nyp", Z)

In [19]:
print("Normal Array:\n", X)
print("Normalized Array:\n", Z)

Normal Array:
 [[0.72145439 0.10128368 0.17771835 0.43791404 0.25549533]
 [0.5965117  0.49385104 0.93303204 0.18387156 0.56162949]
 [0.35627427 0.20324525 0.75932104 0.5465047  0.97133986]
 [0.07184414 0.11502447 0.59969255 0.66423107 0.14246451]
 [0.80826518 0.77269465 0.65875663 0.15304629 0.96770361]]
Normalized Array:
 [[ 0.79740429 -1.34037258 -1.07689631 -0.17998144 -0.808793  ]
 [ 0.36671709  0.01283777  1.52672899 -1.05568571  0.24647537]
 [-0.4614001  -0.98890309  0.92793361  0.19433903  1.65877904]
 [-1.44185297 -1.29300702  0.37768172  0.60015104 -1.19841905]
 [ 1.09664788  0.97403348  0.5812802  -1.16194281  1.64624458]]
